sudo: required
services: 
    - docker 

before_install:
    - docker build -t codixir/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true codixir/react-test npm test

language: generic 

after_success:
    - docker build -t codixir/fibo-client ./client
    - docker build -t codixir/fibo-nginx ./nginx
    - docker build -t codixir/fibo-server ./server
    - docker build -t codixir/fibo-worker ./worker

# Log in to docker CLI 

    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
#Take those images and push them to docker hub
    - docker push codixir/fibo-client
    - docker push codixir/fibo-nginx
    - docker push codixir/fibo-server
    - docker push codixir/fibo-worker
